### ISSUE TITLE
keyword parsing

### ISSUE THREAD

**Issue by dragoncoder047** [technoblogy/ulisp#68]
maybe not a bug per se, but here is another inconsistency with Common Lisp:

Common Lisp:
```
CL-USER> :a:a:a
Parse error: too many colons in token ":a:a:a"
```

uLisp (4.6):
```
> :a:a:a
:a:a:a
```

**Comment by technoblogy** [comment]
Since uLisp is so different from Common Lisp in the areas of keywords and packages I think this is OK as it was.
