### ISSUE TITLE
compiling error v4.6

### ISSUE THREAD

**Issue by fighne** [technoblogy/ulisp#71]
Arduino: 1.8.19 (Linux), Board: "Adafruit QT Py ESP32-S2, Enabled, Disabled, Disabled, Internal USB, Enabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi), QIO, 80MHz, 4MB (32Mb), 921600, None, Disabled"

Using library SPI at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/SPI 
Using library Wire at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/Wire 
Using library WiFi at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/WiFi 
Using library SD at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/SD 
Using library FS at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/FS 
Using library LittleFS at version 2.0.0 in folder: /home/fighne/.arduino15/packages/esp32/hardware/esp32/2.0.16/libraries/LittleFS 
exit status 1
'tablesize' was not declared in this scope

**Comment by technoblogy** [comment]
It looks like you're using the Adafruit QT Py ESP32-S2 board. For this board you should use:

https://github.com/technoblogy/ulisp-esp

For details see:

http://www.ulisp.com/show?3TQF
